name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.output-variable }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Publish
        id: publish
        run: echo 'output-variable=test' >> $GITHUB_OUTPUT ';'
      - name: Deploy project
        run: echo "Deploying..."
  newJob:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print jobs
        run: echo "${{ needs.deploy.outputs.script-file }}"
